config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :receive_posts
  resources :give_posts

  root 'give_posts#index'

  get 'new_give_post' => 'give_posts#new'
  get 'new_receive_post' => 'receive_posts#new'

end

app/models/give_post.rb
class GivePost < ActiveRecord::Base
	geocoded_by :location
	after_validation :geocode

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode

	belongs_to :user
end

app/models/receive_post.rb
class ReceivePost < ActiveRecord::Base
	geocoded_by :location
	after_validation :geocode

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :give_posts
  has_many :receive_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def give_post_categories
	  @give_post_categories = GivePost.pluck(:category).sort.uniq!
	  @give_post_categories ||= GivePost.pluck(:category).sort
	end

  def receive_post_categories
    @receive_post_categories = ReceivePost.pluck(:category).sort.uniq!
    @receive_post_categories ||= ReceivePost.pluck(:category).sort
  end
end

app/controllers/give_posts_controller.rb
class GivePostsController < ApplicationController
  before_action :set_give_post, only: [:show, :edit, :update, :destroy]

  # GET /give_posts
  # GET /give_posts.json
  def index
    @give_posts = GivePost.all
  end

  # GET /give_posts/1
  # GET /give_posts/1.json
  def show
  end

  # GET /give_posts/new
  def new
    @give_post = GivePost.new
  end

  # GET /give_posts/1/edit
  def edit
  end

  # POST /give_posts
  # POST /give_posts.json
  def create
    @give_post = GivePost.new(give_post_params)

    respond_to do |format|
      if @give_post.save
        format.html { redirect_to @give_post, notice: 'Give post was successfully created.' }
        format.json { render :show, status: :created, location: @give_post }
      else
        format.html { render :new }
        format.json { render json: @give_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /give_posts/1
  # PATCH/PUT /give_posts/1.json
  def update
    respond_to do |format|
      if @give_post.update(give_post_params)
        format.html { redirect_to @give_post, notice: 'Give post was successfully updated.' }
        format.json { render :show, status: :ok, location: @give_post }
      else
        format.html { render :edit }
        format.json { render json: @give_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /give_posts/1
  # DELETE /give_posts/1.json
  def destroy
    @give_post.destroy
    respond_to do |format|
      format.html { redirect_to give_posts_url, notice: 'Give post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_give_post
      @give_post = GivePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def give_post_params
      params.require(:give_post).permit(:title, :category, :location, :description, :condition, :user_id, :latitude, :longitude)
    end
end

app/controllers/receive_posts_controller.rb
class ReceivePostsController < ApplicationController
  before_action :set_receive_post, only: [:show, :edit, :update, :destroy]

  # GET /receive_posts
  # GET /receive_posts.json
  def index
    @receive_posts = ReceivePost.all
  end

  # GET /receive_posts/1
  # GET /receive_posts/1.json
  def show
  end

  # GET /receive_posts/new
  def new
    @receive_post = ReceivePost.new
  end

  # GET /receive_posts/1/edit
  def edit
  end

  # POST /receive_posts
  # POST /receive_posts.json
  def create
    @receive_post = ReceivePost.new(receive_post_params)

    respond_to do |format|
      if @receive_post.save
        format.html { redirect_to @receive_post, notice: 'Receive post was successfully created.' }
        format.json { render :show, status: :created, location: @receive_post }
      else
        format.html { render :new }
        format.json { render json: @receive_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receive_posts/1
  # PATCH/PUT /receive_posts/1.json
  def update
    respond_to do |format|
      if @receive_post.update(receive_post_params)
        format.html { redirect_to @receive_post, notice: 'Receive post was successfully updated.' }
        format.json { render :show, status: :ok, location: @receive_post }
      else
        format.html { render :edit }
        format.json { render json: @receive_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receive_posts/1
  # DELETE /receive_posts/1.json
  def destroy
    @receive_post.destroy
    respond_to do |format|
      format.html { redirect_to receive_posts_url, notice: 'Receive post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receive_post
      @receive_post = ReceivePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receive_post_params
      params.require(:receive_post).permit(:title, :category, :location, :description, :condition, :user_id, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/give_posts_helper.rb
module GivePostsHelper
end

app/helpers/receive_posts_helper.rb
module ReceivePostsHelper
end

app/views/give_posts/_form.html.erb
<%= form_for(@give_post) do |f| %>
  <% if @give_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@give_post.errors.count, "error") %> prohibited this give_post from being saved:</h2>

      <ul>
      <% @give_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: "Enter post title", autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select(:category, [["Car Seats", "Car Seats"], ["Strollers, & Trailers", "Strollers, & Trailers"], ["Diapering", "Diapering"], ["Monitors & Nursery", "Monitors & Nursery"], ["Feeding", "Feeding"], ["Carriers & Wraps", "Carriers & Wraps"], ["Bedding", "Carriers & Wraps"]], {include_blank: "Select category"}) %>
  </div>
  <div class="form-group">
    <%= f.select(:age_range, [['Newborn', 1], ['Infant', 2], ['Toddler', 3], ['Child', 4]], {include_blank: "Select age range"}) %>
  </div>
  <div class="form-group">
    <%= f.text_field :location, placeholder: "Enter location", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Enter description", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :condition, placeholder: "Enter condition", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/give_posts/edit.html.erb
<h1>Editing Give Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @give_post %> |
<%= link_to 'Back', give_posts_path %>

app/views/give_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Give Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Age Range</th>
      <th>Location</th>
      <th>Description</th>
      <th>Condition</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @give_posts.each do |give_post| %>
      <tr>
        <td><%= give_post.title %></td>
        <td><%= give_post.category %></td>
        <td><%= give_post.age_range %></td>
        <td><%= give_post.location %></td>
        <td><%= give_post.description %></td>
        <td><%= give_post.condition %></td>
        <td><%= give_post.user_id %></td>
        <td><%= link_to 'Show', give_post %></td>
        <td><%= link_to 'Edit', edit_give_post_path(give_post) %></td>
        <td><%= link_to 'Destroy', give_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Give Post', new_give_post_path %>

app/views/give_posts/new.html.erb
<h1>New Give Post</h1>

<%= render 'form' %>

<%= link_to 'Back', give_posts_path %>

app/views/give_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @give_post.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @give_post.category %>
</p>

<p>
  <strong>Location:</strong>
  <%= @give_post.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @give_post.description %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @give_post.condition %>
</p>

<p>
  <strong>User:</strong>
  <%= @give_post.user_id %>
</p>

<%= link_to 'Edit', edit_give_post_path(@give_post) %> |
<%= link_to 'Back', give_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Sharing Grace</title>

	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= csrf_meta_tags %>

<body>

	<header class="page-header">
		<nav class="navbar navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<%= link_to "Sharing Grace", root_path, class: "navbar-brand" %>
				</div>
				<ul class="nav navbar-nav navbar-left">
					<li>
						<%= link_to "My Account", edit_user_registration_path %>
					</li>
					<% if GivePost.all != nil && GivePost.all.length > 0 %>	
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aira-haspopup="true" aria-expanded="false">Give Posts<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to "New Give Post", new_give_post_path %></li> 
								<% @give_post_categories.each do |category| %>
									<li><%= link_to category, category %></li>
								<% end %>
							</ul>
						</li>
					<% end %>
					<% if ReceivePost.all != nil && ReceivePost.all.length > 0 %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aira-haspopup="true" aria-expanded="false">Receive Posts<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to "New Receive Post", new_receive_post_path %></li>
								<% @receive_post_categories.each do |post| %>
									<li><%= link_to category, category %></li>
								<% end %>
							</ul>
						</li>
					<% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li>
							<%= link_to "Edit Profile", edit_user_registration_path %>
						</li>
						<li>
							<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
						</li>
					<% else %>
						<li>
							<%= link_to "Sign Up", new_user_registration_path %>
						</li>
						<li>
							<%= link_to "Forgot Password", new_user_password_path, method: :delete %>
						</li>                   
					<% end %>
				</ul>
			</div>
		</nav>
	</header>

	<main>
		<div class="container">
		  <%= yield %>
		</div>
	</main>

  <footer class="page-footer navbar-fixed-bottom text-center">
		<div class="container-fluid">
			<p>&copy; Androit Development, 2016</p>
		</div>
	</footer>

	<%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.google_api_key}' %>

	<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/receive_posts/_form.html.erb
<%= form_for(@receive_post) do |f| %>
  <% if @receive_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receive_post.errors.count, "error") %> prohibited this receive_post from being saved:</h2>

      <ul>
      <% @receive_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: "Enter post title", autofocus: "true", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select(:category, [["Car Seats", "Car Seats"], ["Strollers, & Trailers", "Strollers, & Trailers"], ["Diapering", "Diapering"], ["Monitors & Nursery", "Monitors & Nursery"], ["Feeding", "Feeding"], ["Carriers & Wraps", "Carriers & Wraps"], ["Bedding", "Carriers & Wraps"]], {include_blank: "Select category"}) %>
  </div>
  <div class="form-group">
    <%= f.select(:age_range, [['Newborn', 1], ['Infant', 2], ['Toddler', 3], ['Child', 4]], {include_blank: "Select age range"}) %>
  </div>
  <div class="form-group">
    <%= f.text_field :location, placeholder: "Enter location", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Enter description", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :condition, placeholder: "Enter condition", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/receive_posts/edit.html.erb
<h1>Editing Receive Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @receive_post %> |
<%= link_to 'Back', receive_posts_path %>

app/views/receive_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Receive Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Age Range</th>
      <th>Location</th>
      <th>Description</th>
      <th>Condition</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receive_posts.each do |receive_post| %>
      <tr>
        <td><%= receive_post.title %></td>
        <td><%= receive_post.category %></td>
        <td><%= receive_post.age_range %></td>
        <td><%= receive_post.location %></td>
        <td><%= receive_post.description %></td>
        <td><%= receive_post.condition %></td>
        <td><%= receive_post.user_id %></td>
        <td><%= link_to 'Show', receive_post %></td>
        <td><%= link_to 'Edit', edit_receive_post_path(receive_post) %></td>
        <td><%= link_to 'Destroy', receive_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receive Post', new_receive_post_path %>

app/views/receive_posts/new.html.erb
<h1>New Receive Post</h1>

<%= render 'form' %>

<%= link_to 'Back', receive_posts_path %>

app/views/receive_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @receive_post.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @receive_post.category %>
</p>

<p>
  <strong>Location:</strong>
  <%= @receive_post.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @receive_post.description %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @receive_post.condition %>
</p>

<p>
  <strong>User:</strong>
  <%= @receive_post.user_id %>
</p>

<%= link_to 'Edit', edit_receive_post_path(@receive_post) %> |
<%= link_to 'Back', receive_posts_path %>